---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv000
  labels:
   accessModes: RWO
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /containers/pv/pv000
