apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: head
spec:
  replicas: 1
  template:
    metadata:
      name: head
      labels:
        app: head
    spec:
      containers:
        - name: app
          ports:
            - name: http
              containerPort: 9100
          image: mobz/elasticsearch-head:5
